added pytests and worflow test logic

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -53,7 +53,6 @@ jobs:
       - name: Check Container Status
         if: always()
         run: |
-          exit 1
           running=$(docker-compose ps --services --filter "status=running")
           services=$(docker-compose ps --services)
           if [ "$running" == "$services" ]; then
@@ -73,6 +72,14 @@ jobs:
         run: |
           pytest -v tests/assn3_tests.py > assn3_test_results.txt
         continue-on-error: true
+      - name: Check test results
+      run: |
+        if grep -q "failed" assn3_test_results.txt; then 
+          echo "tests failed" >> log.txt
+          exit 1
+        else
+          echo "tests succeeded" >> log.txt
+        fis
       - name: Upload Log File
         if: always()
         uses: actions/upload-artifact@v3
